name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install prerequisites
        run: |
          sudo apt-get install libxkbcommon-dev
          make install

      - name: Run CI
        run: make ci
